#ifndef acromegaly_CONFIG_H
#define acromegaly_CONFIG_H

/**
 * Just for debug purposes - instead of reading ticks from desk movement, could be generated by MCU
 */
#define USE_TICK_GENERATOR false
#define DEBUG 0

/** Value used to convert ticks count to more recognizable unit, broadcasted by status service.
 * In this case, it's fraction 1*10e-6, where one unit of multiplied ticks equals 1um.
 */
#define TICK_TO_HEIGHT_MULTI 525

/**
 * Value in nanometers of minimal countertop position over ground
 */
#define BASE_HEIGHT 834000 

/**
 * The total number of ticks required to achieve a desk maximum height
 */
#define TICKS_UPPER_LIMIT 816
#define TICK_LOWER_LIMIT 0

#endif
